version: '3.7'

services:
    web:
        build: ./web
        ports:
            - '8080:8000'
        volumes: 
            - ./web/app:/app        
        env_file: .env
        depends_on:
            - db
        command: python manage.py runserver 0.0.0.0:8000

    db:
        restart: always
        image: postgres:10-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env

volumes:
    postgres_data:
